# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1422912c8875ad2bc2109352d11b050274c8a85465e7c9a3c43821f0486169d2cec404933846efa3dc4880ae1abb3ff5cada131c068c21d4b3b9d243fa9b39d

test:
  secret_key_base: 499c8242f4422f990e1a93790f8e6e42d06651bf3f34be0163c8afff463da63a2c40130f238d6f7f90a2f0b7b585acb6f8874dad2cd445a081fadc70c855d8e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
